/* Automatic generated by './build/bin/build-entry.js' */

import DqLoading from './packages/load';
// var DqLoading = require('./packages/load');

const components = [
  DqLoading
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

// module.exports = {
//   install,
//   DqLoading
// };
export default DqLoading;